#!/bin/sh

function init() {
  upstream="https://github.com/PocketMine/PocketMine-MP.git"
  local url="$1" ; shift
  if [ -z "$url" ] ; then
    url="$upstream"
  fi

  if [ ! -d PocketMine-MP ] ; then
    git clone "$url" PocketMine-MP
    (
	    cd PocketMine-MP || exit 1
	    git submodule init
	    git submodule update

      if [ "$url" != "$upstream" ] ; then
        # This is a fork!
        git remote add upstream "$upstream"
        git fetch upstream
        echo 'Syncing with:'
        echo '  git fetch upstream'
        echo '  git checkout master'
        echo '  git merge upstream/master'
      fi
    )
  else
    echo "PocketMine-MP already exists!"
  fi
}
function pull() {
    if [ ! -d PocketMine-MP ] ; then
	echo "PocketMine-MP does not exist!"
    else
	(
	    cd PocketMine-MP || exit 1
	    git pull
	    git submodule update
	)
    fi
}

if [ -z "$*" ] ; then
  (
    echo "Usage:"
    echo " - init : initialize PocketMine-MP folder"
    echo " - pull : pull pocketmine updates (including modules)"
  ) 1>&2
  exit 1
fi

"$@"
